# coding: utf-8

"""
    Directory-v3

    Welcome on the documentation for the Directory v3 API. 

    The version of the OpenAPI document: 1.0
    Contact: developers@lucca.fr
    Created by: https://www.lucca.fr
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from lucca_directory_python_sdk import schemas  # noqa: F401


class UsersCreateNewUserResponseHabilitedRoles(
    schemas.ListSchema
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """


    class MetaOapg:
        
        @staticmethod
        def items() -> typing.Type['UsersCreateNewUserResponseHabilitedRolesItem']:
            return UsersCreateNewUserResponseHabilitedRolesItem

    def __new__(
        cls,
        arg: typing.Union[typing.Tuple['UsersCreateNewUserResponseHabilitedRolesItem'], typing.List['UsersCreateNewUserResponseHabilitedRolesItem']],
        _configuration: typing.Optional[schemas.Configuration] = None,
    ) -> 'UsersCreateNewUserResponseHabilitedRoles':
        return super().__new__(
            cls,
            arg,
            _configuration=_configuration,
        )

    def __getitem__(self, i: int) -> 'UsersCreateNewUserResponseHabilitedRolesItem':
        return super().__getitem__(i)

from lucca_directory_python_sdk.model.users_create_new_user_response_habilited_roles_item import UsersCreateNewUserResponseHabilitedRolesItem
