# coding: utf-8

"""
    Directory-v3

    Welcome on the documentation for the Directory v3 API. 

    The version of the OpenAPI document: 1.0
    Contact: developers@lucca.fr
    Created by: https://www.lucca.fr
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from lucca_directory_python_sdk import schemas  # noqa: F401


class UsersUpdateByIdRequestUserWorkCyclesItem(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)
    """


    class MetaOapg:
        
        class properties:
            id = schemas.IntSchema
            startsOn = schemas.StrSchema
            endsOn = schemas.StrSchema
            workCycleId = schemas.IntSchema
            __annotations__ = {
                "id": id,
                "startsOn": startsOn,
                "endsOn": endsOn,
                "workCycleId": workCycleId,
            }
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["id"]) -> MetaOapg.properties.id: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["startsOn"]) -> MetaOapg.properties.startsOn: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["endsOn"]) -> MetaOapg.properties.endsOn: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["workCycleId"]) -> MetaOapg.properties.workCycleId: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["id", "startsOn", "endsOn", "workCycleId", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["id"]) -> typing.Union[MetaOapg.properties.id, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["startsOn"]) -> typing.Union[MetaOapg.properties.startsOn, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["endsOn"]) -> typing.Union[MetaOapg.properties.endsOn, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["workCycleId"]) -> typing.Union[MetaOapg.properties.workCycleId, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["id", "startsOn", "endsOn", "workCycleId", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        id: typing.Union[MetaOapg.properties.id, decimal.Decimal, int, schemas.Unset] = schemas.unset,
        startsOn: typing.Union[MetaOapg.properties.startsOn, str, schemas.Unset] = schemas.unset,
        endsOn: typing.Union[MetaOapg.properties.endsOn, str, schemas.Unset] = schemas.unset,
        workCycleId: typing.Union[MetaOapg.properties.workCycleId, decimal.Decimal, int, schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'UsersUpdateByIdRequestUserWorkCyclesItem':
        return super().__new__(
            cls,
            *args,
            id=id,
            startsOn=startsOn,
            endsOn=endsOn,
            workCycleId=workCycleId,
            _configuration=_configuration,
            **kwargs,
        )
