# coding: utf-8

"""
    Directory-v3

    Welcome on the documentation for the Directory v3 API. 

    The version of the OpenAPI document: 1.0
    Contact: developers@lucca.fr
    Created by: https://www.lucca.fr
"""

from lucca_directory_python_sdk.paths.api_v3_users.post import CreateNewUser
from lucca_directory_python_sdk.paths.api_v3_users_user_id.get import GetById
from lucca_directory_python_sdk.paths.api_v3_users.get import ListExcludedFormer
from lucca_directory_python_sdk.paths.api_v3_users_user_id.put import UpdateById
from lucca_directory_python_sdk.apis.tags.users_api_raw import UsersApiRaw


class UsersApi(
    CreateNewUser,
    GetById,
    ListExcludedFormer,
    UpdateById,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: UsersApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = UsersApiRaw(api_client)
