# coding: utf-8

# flake8: noqa

# import all models into this package
# if you have many models here with many references from one model to another this may
# raise a RecursionError
# to avoid this, import only the models that you directly need like:
# from from lucca_directory_python_sdk.model.pet import Pet
# or import this package, but before doing it, use:
# import sys
# sys.setrecursionlimit(n)

from lucca_directory_python_sdk.model.user import User
from lucca_directory_python_sdk.model.user_application_data import UserApplicationData
from lucca_directory_python_sdk.model.user_application_data_profile_figgo import UserApplicationDataProfileFiggo
from lucca_directory_python_sdk.model.user_application_data_profile_utime import UserApplicationDataProfileUtime
from lucca_directory_python_sdk.model.user_calendar import UserCalendar
from lucca_directory_python_sdk.model.user_culture import UserCulture
from lucca_directory_python_sdk.model.user_department import UserDepartment
from lucca_directory_python_sdk.model.user_habilited_roles import UserHabilitedRoles
from lucca_directory_python_sdk.model.user_legal_entity import UserLegalEntity
from lucca_directory_python_sdk.model.user_manager import UserManager
from lucca_directory_python_sdk.model.user_picture import UserPicture
from lucca_directory_python_sdk.model.user_role_principal import UserRolePrincipal
from lucca_directory_python_sdk.model.user_user_work_cycles import UserUserWorkCycles
from lucca_directory_python_sdk.model.users_create_new_user_response import UsersCreateNewUserResponse
from lucca_directory_python_sdk.model.users_create_new_user_response_habilited_roles import UsersCreateNewUserResponseHabilitedRoles
from lucca_directory_python_sdk.model.users_create_new_user_response_habilited_roles_item import UsersCreateNewUserResponseHabilitedRolesItem
from lucca_directory_python_sdk.model.users_create_new_user_response_user_work_cycles import UsersCreateNewUserResponseUserWorkCycles
from lucca_directory_python_sdk.model.users_create_new_user_response_user_work_cycles_item import UsersCreateNewUserResponseUserWorkCyclesItem
from lucca_directory_python_sdk.model.users_get_by_id_response import UsersGetByIdResponse
from lucca_directory_python_sdk.model.users_get_by_id_response_calendar import UsersGetByIdResponseCalendar
from lucca_directory_python_sdk.model.users_get_by_id_response_culture import UsersGetByIdResponseCulture
from lucca_directory_python_sdk.model.users_get_by_id_response_department import UsersGetByIdResponseDepartment
from lucca_directory_python_sdk.model.users_get_by_id_response_habilited_roles import UsersGetByIdResponseHabilitedRoles
from lucca_directory_python_sdk.model.users_get_by_id_response_habilited_roles_item import UsersGetByIdResponseHabilitedRolesItem
from lucca_directory_python_sdk.model.users_get_by_id_response_legal_entity import UsersGetByIdResponseLegalEntity
from lucca_directory_python_sdk.model.users_get_by_id_response_manager import UsersGetByIdResponseManager
from lucca_directory_python_sdk.model.users_get_by_id_response_picture import UsersGetByIdResponsePicture
from lucca_directory_python_sdk.model.users_get_by_id_response_role_principal import UsersGetByIdResponseRolePrincipal
from lucca_directory_python_sdk.model.users_get_by_id_response_user_work_cycles import UsersGetByIdResponseUserWorkCycles
from lucca_directory_python_sdk.model.users_get_by_id_response_user_work_cycles_item import UsersGetByIdResponseUserWorkCyclesItem
from lucca_directory_python_sdk.model.users_list_excluded_former_response import UsersListExcludedFormerResponse
from lucca_directory_python_sdk.model.users_list_excluded_former_response_items import UsersListExcludedFormerResponseItems
from lucca_directory_python_sdk.model.users_list_excluded_former_response_items_item import UsersListExcludedFormerResponseItemsItem
from lucca_directory_python_sdk.model.users_list_excluded_former_response_items_item_calendar import UsersListExcludedFormerResponseItemsItemCalendar
from lucca_directory_python_sdk.model.users_list_excluded_former_response_items_item_culture import UsersListExcludedFormerResponseItemsItemCulture
from lucca_directory_python_sdk.model.users_list_excluded_former_response_items_item_department import UsersListExcludedFormerResponseItemsItemDepartment
from lucca_directory_python_sdk.model.users_list_excluded_former_response_items_item_habilited_roles import UsersListExcludedFormerResponseItemsItemHabilitedRoles
from lucca_directory_python_sdk.model.users_list_excluded_former_response_items_item_habilited_roles_item import UsersListExcludedFormerResponseItemsItemHabilitedRolesItem
from lucca_directory_python_sdk.model.users_list_excluded_former_response_items_item_legal_entity import UsersListExcludedFormerResponseItemsItemLegalEntity
from lucca_directory_python_sdk.model.users_list_excluded_former_response_items_item_manager import UsersListExcludedFormerResponseItemsItemManager
from lucca_directory_python_sdk.model.users_list_excluded_former_response_items_item_picture import UsersListExcludedFormerResponseItemsItemPicture
from lucca_directory_python_sdk.model.users_list_excluded_former_response_items_item_role_principal import UsersListExcludedFormerResponseItemsItemRolePrincipal
from lucca_directory_python_sdk.model.users_list_excluded_former_response_items_item_user_work_cycles import UsersListExcludedFormerResponseItemsItemUserWorkCycles
from lucca_directory_python_sdk.model.users_list_excluded_former_response_items_item_user_work_cycles_item import UsersListExcludedFormerResponseItemsItemUserWorkCyclesItem
from lucca_directory_python_sdk.model.users_update_by_id_request import UsersUpdateByIdRequest
from lucca_directory_python_sdk.model.users_update_by_id_request_habilited_roles import UsersUpdateByIdRequestHabilitedRoles
from lucca_directory_python_sdk.model.users_update_by_id_request_habilited_roles_item import UsersUpdateByIdRequestHabilitedRolesItem
from lucca_directory_python_sdk.model.users_update_by_id_request_user_work_cycles import UsersUpdateByIdRequestUserWorkCycles
from lucca_directory_python_sdk.model.users_update_by_id_request_user_work_cycles_item import UsersUpdateByIdRequestUserWorkCyclesItem
